version: '3'
services:
  web:
    # Rather than running `npm install` in the container after booting, we
    # run `npm install` in the Docker image build process.
    build: .
    entrypoint:
      - "/usr/src/app/node_modules/.bin/nodemon"
      - "/usr/src/app/server.js"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - "./app:/usr/src/app/app"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
